version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci
  build:
    commands:
      - echo Building application...
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  base-directory: dist
  files:
    - '**/*'
    - package.json
    - package-lock.json
    - node_modules/**/*
    - Procfile

cache:
  paths:
    - node_modules/**/*